name: llama_dart
description: "Supercharge your app with offline AI capabilities, powered by llama.cpp."
version: 0.0.1
homepage: https://brutalcoding.com

environment:
  sdk: '>=3.2.0-199.0.dev <4.0.0'

dependencies:
  cli_config: ^0.1.2
  logging: ^1.2.0
  native_assets_cli: ^0.2.0
  native_toolchain_c: ^0.2.5

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^9.0.1
  flutter_lints: ^2.0.3
  test: ^1.24.6
